### ISSUE TITLE
Several questions on the code design

### ISSUE THREAD

**Issue by lin108** [gershhub/groundstation-receiver#1]

**Comment by gershhub** [comment]
Hey thanks for the note! 

1. The TLE file update process (downloading from the server) only needs to happen once per week, if that, since the telemetry is quite predictable. My thought was that python reading from the local file would be less risky than having a download from remote in the loop. The file can be separately downloaded by an independent shell script loaded in a cron job or with a systemd timer. If that fails, the prediction would continue using the old TLE with some error but not much. But you're right, either way would work fine, and the (very small) risk of a collision over the file would be mitigated by putting the download in the loop.

2.  Yeah good catch... and that's just lazy coding. There's wasted cycles running predict every loop, but that's only running a few times a day and there's not much to it.

**Comment by lin108** [comment]
Got it, thanks for your response!!
